import re
import json
from gmbotmodules.mymodules import *

moduleName = "Compliment"
helpString = "/comp [someone or something] will generate a compliment"

#Compliments Generated by AI
def checkMessage(message):
    if re.search(r'^/comp\b', message['text']):
        logusage()
        compliment = random.choice(complimentArray['compliments'])
        sendMessage(text=f"{message['text'][5:]}{', ' if message['text'][5:].strip() else ' '}{compliment}", message=message)
        return True
    return False

with open('res/compArray.json', 'r', encoding='utf-8') as file:
    complimentArray = json.load(file)